### ISSUE TITLE
Crash with mekanism(?)

### ISSUE THREAD

**Issue by Chromogen** [Darkhax-Minecraft/Bookshelf#77] opened 2017-06-18 15:48 UTC
hey there, i had a problem when updating bookshelf. something crashing the game. all mods work fine, it is definetly bookshelf update. already tested minecraft on all mods seperate t pinpoint it.

Bookshelf-1.11.2-1.5.0.371  -> Bookshelf-1.11.2-2.0.0.388

report is this:
https://pastebin.com/LAGEb0zN

sorry that ic ant provide any more info
thx :)

**Comment by IchigoGames** [comment] 2017-06-18 17:56
i got the same crash when i updated bookshlf

**Comment by darkhax** [comment] 2017-06-18 18:26
Duplicate of https://github.com/aidancbrady/Mekanism/issues/4414 Issue is in Mekanism and not Bookshelf.

**Closed by darkhax** 2017-06-18 18:26 UTC
Labels: duplicate
