### ISSUE TITLE
Console spamming

### ISSUE THREAD

**Issue by phit** [Darkhax-Minecraft/Bookshelf#54] opened 2016-11-06 18:26 UTC
my server console started spamming this multiple times a second
```06.11 13:24:03 [Server] Bookshelf A TileEntity at %s in world %s failed a client update tick!```
last server log file is over 100mb now

Bookshelf-1.10.2-1.4.2.331.jar
FTBserver-1.10.2-12.18.2.2119-universal.jar
pack is ftb infinity lite

not sure if relevant but the server is running sponge 
spongeforge-1.10.2-2107-6.0.0-BETA-1871.jar

**Comment by darkhax** [comment] 2016-11-06 22:23
Is there any text accompanying these lines? This happens every time a tickable tile entity from one of my mods fails a tick. Prevents the world from corrupting and such.

**Comment by phit** [comment] 2016-11-07 01:08
no, just that line

**Comment by darkhax** [comment] 2017-01-09 11:39
Closing as unable to reproduce. Likely an issue with world corruption.

**Closed by darkhax** 2017-01-09 11:39 UTC
