### ISSUE TITLE
Logs consistently throwing error about missing tags with the namespace `c` on startup

### ISSUE THREAD

**Issue by JadeJuno** [Darkhax-Minecraft/Bookshelf#184] opened 2022-05-06 22:19 UTC
Everytime I open Minecraft with the Bookshelf library, I get these errors on the logs:
```
[18:12:00] [Render thread/ERROR]: Couldn't load tag bookshelf:shears as it is missing following references: #c:shears (from Bookshelf)
[18:12:00] [Render thread/ERROR]: Couldn't load tag bookshelf:stones as it is missing following references: #c:stones (from Bookshelf), #c:stone (from Bookshelf)
[18:12:00] [Render thread/ERROR]: Couldn't load tag bookshelf:strings as it is missing following references: #c:strings (from Bookshelf), #c:string (from Bookshelf)
[18:12:00] [Render thread/ERROR]: Couldn't load tag bookshelf:fence_gates as it is missing following references: #c:fence_gates (from Bookshelf)
[18:12:00] [Render thread/ERROR]: Couldn't load tag bookshelf:slime_balls as it is missing following references: #c:slimeballs (from Bookshelf), #c:slime_balls (from Bookshelf)
```
They aren't really bad, I guess, but they're still kind of annoying nonetheless.

**Comment by Darkhax** [comment] 2022-05-06 23:34
Thanks for reporting this, it's definitely an issue. Which modloader are you using, and which version of Bookshelf?

**Comment by JadeJuno** [comment] 2022-05-07 00:13
Fabric. Version 13.0.13 for 1.18.2

**Comment by Darkhax** [comment] 2022-05-07 01:45
I can not reproduce this issue using the versions you listed. It's possible another mod you have installed is removing the tags or you are possibly missing the Fabirc API.

**Comment by JadeJuno** [comment] 2022-05-07 02:11
I believe it could be Autotag, but the Minecraft Launcher has decided that it doesn't want to log me into my account, so I can't check right now. Here's a [CurseForge Link](https://www.curseforge.com/minecraft/mc-mods/autotag) to the mod if you want to check it yourself.

Edit: Just confirmed, it was indeed Autotag.

**Comment by apace100** [comment] 2022-05-07 07:40
Can't reproduce with Fabric API 0.51.1, Bookshelf 13.0.13 and AutoTag 1.1.0 (on Minecraft 1.18.2, using Fabric Loader 0.13.3).

I did notice these errors before however by loading FAPI 0.51.1, Bookshelf 13.0.13 and Inspecio 1.3.0. Though I'm not entirely sure, I suppose the error results from Inspecio loading up the Quilt Standard Libraries (edit: as it also happens with other mods' tags).

I can report that this is not a serious issue - the errors only appear on startup, and when loading a world the tags load properly and exist in the game.

**Comment by JadeJuno** [comment] 2022-05-07 17:32
Oh yeah, I just noticed I had uninstalled Bookshelf too before uninstalling Autotag... My bad.
Installing it back without Autotag still brings the error and uninstalling Inspecio solves it. Also yeah, it is only on startup. When loading a world, the tags do exist
![image](https://user-images.githubusercontent.com/53577918/167265343-97a12e48-99a7-403d-996a-23d719a7655e.png)

**Comment by Darkhax** [comment] 2022-05-07 18:18
Thanks for looking further into this. It seems the issue is not with Bookshelf so I will close this report.

**Closed as completed by Darkhax** 2022-05-07 18:18 UTC
