### ISSUE TITLE
[1.11.2] Incompatibility with Tiny Progressions

### ISSUE THREAD

**Issue by EmosewaGamer** [Darkhax-Minecraft/Bookshelf#76] opened 2017-06-17 09:34 UTC
After version 2.0, the core has been incompatible with Tiny Progressions. As this is a core mod I decided to post the issue here.

https://pastebin.com/26tbeEk1

**Comment by Thiana** [comment] 2017-06-17 12:53
This crash is occurring with Mekanism as well.

http://openeye.openmods.info/crashes/8e56b4649bf41cccd7f5a5ed038383ac

**Comment by darkhax** [comment] 2017-06-17 16:44
Duplicate of https://github.com/Darkhax-Minecraft/Bookshelf/issues/72 and https://github.com/aidancbrady/Mekanism/issues/4414 issue is in those mods and not Bookshelf. They've both said they've fixed the issue and an update will come here.

**Closed by darkhax** 2017-06-17 16:44 UTC
Labels: duplicate
