### ISSUE TITLE
[1.11.2] Mekanism/Bookshelf Crash

### ISSUE THREAD

**Issue by MokahTGS** [Darkhax-Minecraft/Bookshelf#78] opened 2017-06-23 20:32 UTC
https://github.com/aidancbrady/Mekanism/issues/4489

I reported this over at the Mekanism Github but just linking it in case there is something I missed.

**Comment by thommy101** [comment] 2017-06-23 20:49
As stated on the Mekanism github, has been reported before and it's the fault of Mekanism. 

It is fixed and will be released in the next version of Mekanism.

**Comment by darkhax** [comment] 2017-06-23 22:58
Duplicate of https://github.com/aidancbrady/Mekanism/issues/4414 Issue is in Mekanism.

**Closed by darkhax** 2017-06-23 22:58 UTC
