### ISSUE TITLE
Mekanism compatibility on 1.11.2

### ISSUE THREAD

**Issue by kragnoth** [Darkhax-Minecraft/Bookshelf#75] opened 2017-06-16 21:54 UTC
https://pastebin.com/WzrHRqyn

Pastebin of crashlog.  It looks like bookshelf edits a method that mekanism depends on.  This is for any version newer than 371 released may 10th.

Unfortunately, this means I can't download the latest version of bookshelf of dark utilities, as mekanism crashes hard.

If you believe this to be a mekanism issue, I will try to link an issue on their git repo as well.  Thanks

**Comment by darkhax** [comment] 2017-06-16 22:08
Duplicate of https://github.com/aidancbrady/Mekanism/issues/4414 It has been reported and fixed on the latest mekanism version.

**Closed by darkhax** 2017-06-16 22:08 UTC
Labels: duplicate

**Comment by kragnoth** [comment] 2017-06-17 02:34
I'm running 307 and it is still happening.  Wonder what I can do to remedy this on my end then.
